language: node_js
node_js:
- 10
- 12
matrix:
  fast_finish: true
notifications:
  email: false
  slack:
    secure: E8uJzoHF301QO+PAtVGmy6oEh9pc2Hb0W+lscMLU26S7R8qeHWJ9MvZi/SpCHYD6LR4SH+F2Umx5PYfnKsgID0idyzxxXunlj2xKRPmTI4CZdXQEXU0lv/SznilpMWg8YPPrifvwx8ZBSu5m3Vxx+6TTNAWmLo9qtaz5LwIq12eMZHqFSpTrtN7HIpRWW9cRknU/ep2YeqjFiQ/P+BTpnmQOHPYn2ob7jcWEkpGsCB53zd+wgG+26bpXa4csiQbVgjmEn+DBbMTENc9G/bKb8yP9F55e2++3dAn7G1zRnP47OS+4ywK+Vf/zkzcnAfuCgqJF+f7WqR9EPV/d2DIAL+CzYoQyymg5K1V4PP/XzAueHUEDONn7LWuvXUXH3RfbKmPKmhnLEtIAIx5fOwdJNghtH6/DVG7mLWEW1JSvKYUWEShYJXMrdb8usrRpCnMqQCmwQB/gfVeEtMzfP5a0diRzaOwVqyWcx53YjYGhVZaDOqfrgT1Sv91E2QZs09FDY5IE+k9mE4Emsyr9vMFsfOcuSbjUpEm6UVKA5q2cFINiB8falxI/a32WMGIE0PfXQJMFIahcCYYrqdk6Zu9SMRzgkvHujCtqDUnbDilXfKRySxSDfm5lTBpPR5v5jxMdht3a7S9EgffX9uI8ToDdxOJVfwF4MtD3pLqDiquwPXU=
cache:
  directories:
  - "$HOME/.npm"
